import json
from typing import List

from ..schemas import Scene, VideoRequest
from .. import config

try:
    from openai import OpenAI  # type: ignore
except ImportError:
    OpenAI = None  # type: ignore


def _build_fallback_script(req: VideoRequest) -> tuple[str, List[Scene]]:
    """
    Fallback script if OpenAI is not available or fails.

    This still gives you a usable pipeline without any API keys or when the key is invalid.
    """
    base_intro = (
        f"This is a short neutral explainer about {req.topic}, "
        "a topic related to religion or spirituality. "
        "In a real setup this text would be generated by an AI model. "
        "You can customise the script generation logic in script_service.py."
    )
    scenes: List[Scene] = [
        Scene(
            index=1,
            text=f"Intro: In this video, we talk about {req.topic} in a {req.style} style.",
            keywords=[req.topic, "intro", "religion"],
            duration_seconds=req.duration_seconds * 0.25,
        ),
        Scene(
            index=2,
            text="We give a brief background, focusing on what this concept means in a respectful, neutral way.",
            keywords=["background", "meaning"],
            duration_seconds=req.duration_seconds * 0.25,
        ),
        Scene(
            index=3,
            text="We mention a few key elements or practices, without judging or comparing beliefs.",
            keywords=["key points", "practices"],
            duration_seconds=req.duration_seconds * 0.25,
        ),
        Scene(
            index=4,
            text="Finally, we encourage the viewer to learn more from trusted community and scholarly sources.",
            keywords=["outro", "sources"],
            duration_seconds=req.duration_seconds * 0.25,
        ),
    ]
    full_text = base_intro + " " + " ".join(scene.text for scene in scenes)
    return full_text, scenes


def generate_script(req: VideoRequest) -> tuple[str, List[Scene], bool]:
    """
    Generate a narration script and scene breakdown focused on religious topics.

    Returns:
        script_text, scenes, used_ai
        - used_ai = True if OpenAI call succeeded
        - used_ai = False if fallback was used
    """
    # If we obviously can't use OpenAI, go straight to fallback.
    if not config.OPENAI_API_KEY or OpenAI is None:
        script_text, scenes = _build_fallback_script(req)
        return script_text, scenes, False

    client = OpenAI(api_key=config.OPENAI_API_KEY)

    system_prompt = (
        "You are an assistant that writes short, neutral, educational video scripts "
        "about religious and spiritual topics only. "
        "You must be respectful to all beliefs, avoid mockery, and avoid encouraging "
        "viewers to convert, leave, or oppose any faith. "
        "You present information in a balanced, informational way. "
        "Return the result strictly as JSON with the keys: "
        "script_text (string) and scenes (list of objects with keys: index, text, keywords, duration_seconds)."
    )

    user_prompt = (
        f"Create a short script about the religious or spiritual topic: '{req.topic}'.\n"
        f"Style: {req.style}.\n"
        f"Target total duration: about {req.duration_seconds} seconds of spoken narration.\n"
        "Split it into 4–6 short scenes to match vertical social-media video style.\n"
        "IMPORTANT: The scene `text` fields must be natural narration only, "
        "and must NOT include labels like 'Scene 1:' or 'Scene 2:'. "
        "Scene numbering should only appear in the JSON `index` field, not in the `text` itself.\n"
        "Each scene text should be one or two sentences. "
        "Estimate duration_seconds for each scene so the total is close to the requested duration. "
        "Focus on explaining beliefs, practices, or historical context in a neutral and respectful way. "
        "Do NOT tell the viewer what they should believe or which religion is right or wrong."
    )

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            response_format={"type": "json_object"},
        )

        content = response.choices[0].message.content
        data = json.loads(content)

        scenes: List[Scene] = [
            Scene(
                index=int(scene["index"]),
                text=str(scene["text"]),
                keywords=list(scene.get("keywords", [])),
                duration_seconds=float(
                    scene.get("duration_seconds", req.duration_seconds / 4)
                ),
            )
            for scene in data["scenes"]
        ]

        script_text: str = str(data.get("script_text", "")).strip()
        if not script_text:
            raise ValueError("Model returned empty script_text")

        return script_text, scenes, True

    except Exception as e:
        # Any error (invalid key, expired key, network issue) → fallback.
        print(f"[script_service] OpenAI error, using fallback script: {e}")
        script_text, scenes = _build_fallback_script(req)
        return script_text, scenes, False