import json
import math
from typing import List

from ..schemas import Scene, VideoRequest
from .. import config

try:
    from openai import OpenAI  # type: ignore
except ImportError:
    OpenAI = None  # type: ignore


def _build_fallback_script(req: VideoRequest) -> tuple[str, List[Scene]]:
    """
    Fallback script if OpenAI is not available or fails.

    This still gives you a usable pipeline without any API keys or when the key is invalid.
    """
    base_intro = (
        f"This is a short neutral explainer about {req.topic}, "
        "a topic related to religion or spirituality. "
        "In a real setup this text would be generated by an AI model. "
        "You can customise the script generation logic in script_service.py."
    )
    n = max(4, math.ceil(float(req.duration_seconds) / 100.0))
    n = min(n, 12)
    per_scene = max(10.0, min(float(req.duration_seconds) / n, 110.0))
    templates = [
        ("Intro: In this video, we talk about {topic} in a {style} style.", [req.topic, "intro", "religion"]),
        ("We give a brief background, focusing on what this concept means in a respectful, neutral way.", ["background", "meaning"]),
        ("We mention key elements or practices, without judging or comparing beliefs.", ["key points", "practices"]),
        ("We connect historical context and lived tradition in a balanced educational tone.", ["history", "context"]),
        ("We highlight common misunderstandings and clarify them respectfully.", ["clarification", "education"]),
        ("Finally, we encourage viewers to learn more from trusted community and scholarly sources.", ["outro", "sources"]),
    ]
    scenes: List[Scene] = []
    for i in range(n):
        text_t, keywords = templates[i % len(templates)]
        scenes.append(
            Scene(
                index=i + 1,
                text=text_t.format(topic=req.topic, style=req.style),
                keywords=keywords,
                duration_seconds=per_scene,
            )
        )
    full_text = base_intro + " " + " ".join(scene.text for scene in scenes)
    return full_text, scenes


def generate_script(req: VideoRequest) -> tuple[str, List[Scene], bool]:
    """
    Generate a narration script and scene breakdown focused on religious topics.

    Returns:
        script_text, scenes, used_ai
        - used_ai = True if OpenAI call succeeded
        - used_ai = False if fallback was used
    """
    # If we obviously can't use OpenAI, go straight to fallback.
    if not config.OPENAI_API_KEY or OpenAI is None:
        script_text, scenes = _build_fallback_script(req)
        return script_text, scenes, False

    client = OpenAI(api_key=config.OPENAI_API_KEY)

    system_prompt = (
        "You are an assistant that writes short, neutral, educational video scripts "
        "about religious and spiritual topics only. "
        "You must be respectful to all beliefs, avoid mockery, and avoid encouraging "
        "viewers to convert, leave, or oppose any faith. "
        "You present information in a balanced, informational way. "
        "Return the result strictly as JSON with the keys: "
        "script_text (string) and scenes (list of objects with keys: index, text, keywords, duration_seconds)."
    )

    target = float(req.duration_seconds)
    est_lo = max(110, int(target * 2.3))
    est_hi = int(target * 2.85)
    if req.aspect_ratio == "16:9":
        scene_count_guidance = "Split it into 8–14 scenes suitable for a normal YouTube video."
        pacing_guidance = (
            "Allow deeper explanations, brief transitions, and richer context than short-form clips."
        )
    elif req.aspect_ratio == "1:1":
        scene_count_guidance = "Split it into 5–8 scenes suitable for a square social video."
        pacing_guidance = "Keep pacing moderate and clear."
    else:
        scene_count_guidance = "Split it into 4–6 short scenes to match vertical short-form style."
        pacing_guidance = "Keep narration concise, direct, and short-form friendly."

    user_prompt = (
        f"Create a short script about the religious or spiritual topic: '{req.topic}'.\n"
        f"Style: {req.style}.\n"
        f"Target spoken narration duration: ABOUT {target:.0f} seconds TOTAL when read aloud naturally. "
        f"Aim for roughly {est_lo}–{est_hi} substantive words across ALL scenes combined. "
        f"Set EACH scene duration_seconds so their SUM stays within {(target - 8):.0f}–{(target + 12):.0f} seconds "
        "so narration timing matches viewer expectations.\n"
        f"{scene_count_guidance}\n"
        f"{pacing_guidance}\n"
        "IMPORTANT: The scene `text` fields must be natural narration only, "
        "and must NOT include labels like 'Scene 1:' or 'Scene 2:'. "
        "Scene numbering should only appear in the JSON `index` field, not in the `text` itself.\n"
        "Each scene text should be one or two sentences with enough substantive detail to comfortably fill "
        "its duration_seconds allocation (avoid filler that will read too briefly). "
        "Estimate duration_seconds for each scene so the total aligns with the narration target above. "
        "Focus on explaining beliefs, practices, or historical context in a neutral and respectful way. "
        "Do NOT tell the viewer what they should believe or which religion is right or wrong."
    )

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            response_format={"type": "json_object"},
        )

        content = response.choices[0].message.content
        data = json.loads(content)

        scenes: List[Scene] = [
            Scene(
                index=int(scene["index"]),
                text=str(scene["text"]),
                keywords=list(scene.get("keywords", [])),
                duration_seconds=float(
                    scene.get("duration_seconds", req.duration_seconds / 4)
                ),
            )
            for scene in data["scenes"]
        ]

        script_text: str = str(data.get("script_text", "")).strip()
        if not script_text:
            raise ValueError("Model returned empty script_text")

        return script_text, scenes, True

    except Exception as e:
        # Any error (invalid key, expired key, network issue) → fallback.
        print(f"[script_service] OpenAI error, using fallback script: {e}")
        script_text, scenes = _build_fallback_script(req)
        return script_text, scenes, False